"""
PostgreSQL abstraction layer — replaces index.json file I/O.

All functions are synchronous (matching the threaded Flask/wiki stack).
Requires: sqlalchemy>=2.0, psycopg2-binary, pgvector.
Activated only when DATABASE_URL is set in the environment.
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any

logger = logging.getLogger(__name__)

_engine = None


def get_engine():
    global _engine
    if _engine is not None:
        return _engine

    import config
    from sqlalchemy import create_engine
    from sqlalchemy.pool import QueuePool

    url = config.DATABASE_URL
    if not url:
        raise RuntimeError("DATABASE_URL is not set — cannot initialise PostgreSQL engine")

    _engine = create_engine(
        url,
        poolclass=QueuePool,
        pool_size=10,
        max_overflow=20,
        pool_pre_ping=True,
    )
    _init_schema(_engine)
    return _engine


def reset_engine() -> None:
    """Discard the cached engine so the next call to get_engine() re-initialises
    the schema.  Call this whenever the embedding provider changes at runtime so
    the dimension migration check fires with the new vector size."""
    global _engine
    if _engine is not None:
        try:
            _engine.dispose()
        except Exception:
            pass
        _engine = None


def _init_schema(engine) -> None:
    """Create all tables on first connect. Idempotent (IF NOT EXISTS throughout)."""
    from sqlalchemy import text

    with engine.connect() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS pages (
                id                    BIGSERIAL PRIMARY KEY,
                session_id            TEXT NOT NULL,
                title                 TEXT NOT NULL,
                content               TEXT NOT NULL DEFAULT '',
                summary               TEXT NOT NULL DEFAULT '',
                source_doc            TEXT NOT NULL DEFAULT '',
                contradiction_flagged BOOLEAN NOT NULL DEFAULT FALSE,
                variants              JSONB,
                append_count          INT NOT NULL DEFAULT 0,
                char_count            INT NOT NULL DEFAULT 0,
                last_modified         TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (session_id, title)
            )
        """))

        conn.execute(text(
            "CREATE INDEX IF NOT EXISTS pages_session_source_idx ON pages (session_id, source_doc)"
        ))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS relations (
                id         BIGSERIAL PRIMARY KEY,
                session_id TEXT NOT NULL,
                from_title TEXT NOT NULL,
                to_title   TEXT NOT NULL,
                label      TEXT NOT NULL DEFAULT '',
                UNIQUE (session_id, from_title, to_title, label)
            )
        """))

        import config as _cfg
        _emb_dims = _cfg.get_embedding_dimensions()
        conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS page_embeddings (
                session_id TEXT NOT NULL,
                title      TEXT NOT NULL,
                embedding  vector({_emb_dims}),
                PRIMARY KEY (session_id, title)
            )
        """))

        # Dimension migration: if the table already exists but was created with
        # a different vector size (e.g. 1536 default before nemotron/2048 model),
        # drop and recreate.  Embeddings are always re-derivable, so this is safe.
        try:
            row = conn.execute(text("""
                SELECT (regexp_matches(
                    format_type(a.atttypid, a.atttypmod),
                    'vector\\((\\d+)\\)'
                ))[1]::int AS dim
                FROM pg_attribute a
                JOIN pg_class c ON c.oid = a.attrelid
                WHERE c.relname = 'page_embeddings'
                  AND a.attname  = 'embedding'
                  AND NOT a.attisdropped
            """)).fetchone()
            if row and row.dim != _emb_dims:
                logger.warning(
                    "page_embeddings dimension mismatch (DB=%d, config=%d) — "
                    "recreating table (embeddings will be regenerated by backfill)",
                    row.dim, _emb_dims,
                )
                conn.execute(text("DROP INDEX IF EXISTS page_embeddings_hnsw_idx"))
                conn.execute(text("DROP TABLE page_embeddings"))
                conn.execute(text(f"""
                    CREATE TABLE page_embeddings (
                        session_id TEXT NOT NULL,
                        title      TEXT NOT NULL,
                        embedding  vector({_emb_dims}),
                        PRIMARY KEY (session_id, title)
                    )
                """))
        except Exception as _dim_err:
            logger.warning("Could not check page_embeddings dimension: %s", _dim_err)

        # HNSW index for sub-5ms cosine similarity search at 140k+ pages.
        # pgvector ≤ 0.6 enforces a hard 2000-dimension limit on HNSW/IVFFlat.
        # If the configured embedding dimension exceeds 2000, skip the index and
        # fall back to an exact sequential scan — still correct, and fast enough
        # until the wiki grows beyond ~50k pages.  Upgrade pgvector to 0.7+
        # (which raises the limit to 16000) to re-enable the index at higher dims.
        if _emb_dims <= 2000:
            try:
                conn.execute(text("""
                    CREATE INDEX IF NOT EXISTS page_embeddings_hnsw_idx
                    ON page_embeddings
                    USING hnsw (embedding vector_cosine_ops)
                    WITH (m = 16, ef_construction = 64)
                """))
            except Exception as _idx_err:
                logger.warning("Could not create HNSW index (pgvector limit?): %s", _idx_err)
        else:
            logger.info(
                "EMBEDDING_DIMENSIONS=%d > 2000 — skipping HNSW index "
                "(exact cosine scan used instead; upgrade pgvector ≥ 0.7 to re-enable)",
                _cfg.EMBEDDING_DIMENSIONS,
            )

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS ingest_progress (
                session_id TEXT PRIMARY KEY,
                data       JSONB NOT NULL DEFAULT '{}',
                started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        """))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS page_metadata (
                session_id         TEXT NOT NULL,
                title              TEXT NOT NULL,
                governing_law      TEXT,
                jurisdiction       TEXT,
                effective_date     TEXT,
                termination_notice TEXT,
                liability_cap      TEXT,
                ip_ownership       TEXT,
                parties            TEXT,
                auto_renewal       TEXT,
                notice_period      TEXT,
                payment_terms      TEXT,
                matter_reference   TEXT,
                PRIMARY KEY (session_id, title)
            )
        """))

        # Existing DBs created before matter_reference was added won't get it
        # from CREATE TABLE IF NOT EXISTS above — add it explicitly.
        try:
            conn.execute(text("""
                ALTER TABLE page_metadata
                ADD COLUMN IF NOT EXISTS matter_reference TEXT
            """))
        except Exception as _matter_ref_err:
            logger.warning("Could not add matter_reference column (may already exist): %s", _matter_ref_err)

        # S2: FTS column + GIN index for O(log N) cross-reference (Phase 4)
        # Add generated tsvector column to pages if it doesn't exist yet.
        try:
            conn.execute(text("""
                ALTER TABLE pages
                ADD COLUMN IF NOT EXISTS content_tsv TSVECTOR
                    GENERATED ALWAYS AS (to_tsvector('english', content)) STORED
            """))
        except Exception as _tsv_err:
            logger.warning("Could not add content_tsv column (may already exist): %s", _tsv_err)
        try:
            conn.execute(text("""
                CREATE INDEX IF NOT EXISTS pages_content_tsv_gin_idx
                ON pages USING GIN(content_tsv)
            """))
        except Exception as _gin_err:
            logger.warning("Could not create GIN index (may already exist): %s", _gin_err)

        # S4: Structured contradictions table (Phase 4)
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS contradictions (
                id          BIGSERIAL PRIMARY KEY,
                session_id  TEXT NOT NULL,
                page_title  TEXT NOT NULL,
                claim       TEXT,
                value_a     TEXT,
                source_a    TEXT,
                value_b     TEXT,
                source_b    TEXT,
                detected_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS contradictions_session_idx
            ON contradictions (session_id, page_title)
        """))

        # Chat messages table (conversational UX)
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS chat_messages (
                id          BIGSERIAL PRIMARY KEY,
                session_id  TEXT NOT NULL,
                role        TEXT NOT NULL,
                content     TEXT NOT NULL,
                msg_type    TEXT NOT NULL DEFAULT 'text',
                metadata    JSONB,
                created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS chat_messages_session_idx
            ON chat_messages (session_id, created_at)
        """))

        # Source positions table (citation exact-location support)
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS source_positions (
                session_id  TEXT NOT NULL,
                source_doc  TEXT NOT NULL,
                page_num    INT NOT NULL,
                char_start  INT NOT NULL,
                char_end    INT NOT NULL,
                PRIMARY KEY (session_id, source_doc, page_num)
            )
        """))

        conn.commit()


# ---------------------------------------------------------------------------
# Pages
# ---------------------------------------------------------------------------

def get_pages(session_id: str) -> dict[str, dict]:
    """Return all pages for a session as {title: {content, summary, source_doc, ...}}."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("SELECT title, content, summary, source_doc, contradiction_flagged, variants "
                 "FROM pages WHERE session_id = :sid"),
            {"sid": session_id},
        )
        pages: dict[str, dict] = {}
        for row in rows:
            page: dict[str, Any] = {
                "content": row.content,
                "summary": row.summary,
                "source_doc": row.source_doc,
            }
            if row.contradiction_flagged:
                page["contradiction_flagged"] = True
            if row.variants is not None:
                page["variants"] = row.variants
            pages[row.title] = page
        return pages


def get_page(session_id: str, title: str) -> dict | None:
    """Return a single page dict or None if it does not exist."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        row = conn.execute(
            text("SELECT content, summary, source_doc, contradiction_flagged, variants "
                 "FROM pages WHERE session_id = :sid AND title = :title"),
            {"sid": session_id, "title": title},
        ).fetchone()
        if row is None:
            return None
        page: dict[str, Any] = {
            "content": row.content,
            "summary": row.summary,
            "source_doc": row.source_doc,
        }
        if row.contradiction_flagged:
            page["contradiction_flagged"] = True
        if row.variants is not None:
            page["variants"] = row.variants
        return page


def get_page_titles(session_id: str) -> list[str]:
    """Return only page titles for a session (cheaper than get_pages for file-name lookups)."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("SELECT title FROM pages WHERE session_id = :sid"),
            {"sid": session_id},
        )
        return [row.title for row in rows]


def get_all_page_titles_and_content(session_id: str) -> dict[str, str]:
    """Return {title: content} for all pages. Used for the cross-reference pass."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("SELECT title, content FROM pages WHERE session_id = :sid"),
            {"sid": session_id},
        )
        return {row.title: row.content for row in rows}


def count_pages(session_id: str) -> int:
    """Return the number of pages stored for a session."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        result = conn.execute(
            text("SELECT COUNT(*) FROM pages WHERE session_id = :sid"),
            {"sid": session_id},
        ).scalar()
        return result or 0


def count_relations(session_id: str) -> int:
    """Return the number of relations stored for a session."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        result = conn.execute(
            text("SELECT COUNT(*) FROM relations WHERE session_id = :sid"),
            {"sid": session_id},
        ).scalar()
        return result or 0


# ---------------------------------------------------------------------------
# Embeddings (Phase 3 — pgvector search)
# ---------------------------------------------------------------------------

def upsert_embedding(session_id: str, title: str, embedding: list[float]) -> None:
    """Store or update a page embedding vector."""
    from sqlalchemy import text
    engine = get_engine()
    # Format as pgvector literal string: [x1,x2,...] then CAST to vector
    emb_str = "[" + ",".join(f"{x:.8f}" for x in embedding) + "]"
    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO page_embeddings (session_id, title, embedding)
                VALUES (:sid, :title, CAST(:embedding AS vector))
                ON CONFLICT (session_id, title) DO UPDATE SET
                    embedding = EXCLUDED.embedding
            """),
            {"sid": session_id, "title": title, "embedding": emb_str},
        )
        conn.commit()


def search_similar_pages(
    session_id: str, query_embedding: list[float], limit: int = 25
) -> list[str]:
    """Return page titles ordered by cosine similarity to query_embedding.

    Uses the HNSW index for sub-5ms lookup even at 140k+ pages.
    Returns [] if no embeddings exist for this session.
    """
    from sqlalchemy import text
    engine = get_engine()
    emb_str = "[" + ",".join(f"{x:.8f}" for x in query_embedding) + "]"
    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT title
                FROM page_embeddings
                WHERE session_id = :sid
                ORDER BY embedding <=> CAST(:embedding AS vector)
                LIMIT :limit
            """),
            {"sid": session_id, "embedding": emb_str, "limit": limit},
        )
        return [row.title for row in rows]


def count_embeddings(session_id: str) -> int:
    """Return the number of pages with embeddings stored for a session."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        result = conn.execute(
            text("SELECT COUNT(*) FROM page_embeddings WHERE session_id = :sid"),
            {"sid": session_id},
        ).scalar()
        return result or 0


def upsert_page(
    session_id: str,
    title: str,
    content: str,
    summary: str,
    source_doc: str,
    contradiction_flagged: bool = False,
    variants: list | None = None,
) -> None:
    """Insert or fully replace a page row."""
    from sqlalchemy import text
    engine = get_engine()
    variants_json = json.dumps(variants) if variants is not None else None
    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO pages
                    (session_id, title, content, summary, source_doc,
                     contradiction_flagged, variants, append_count, char_count, last_modified)
                VALUES
                    (:sid, :title, :content, :summary, :source_doc,
                     :cf, CAST(:variants AS jsonb), 1, :char_count, now())
                ON CONFLICT (session_id, title) DO UPDATE SET
                    content               = EXCLUDED.content,
                    summary               = EXCLUDED.summary,
                    source_doc            = EXCLUDED.source_doc,
                    contradiction_flagged = EXCLUDED.contradiction_flagged,
                    variants              = EXCLUDED.variants,
                    append_count          = pages.append_count + 1,
                    char_count            = EXCLUDED.char_count,
                    last_modified         = now()
            """),
            {
                "sid": session_id,
                "title": title,
                "content": content,
                "summary": summary,
                "source_doc": source_doc,
                "cf": contradiction_flagged,
                "variants": variants_json,
                "char_count": len(content),
            },
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Relations
# ---------------------------------------------------------------------------

def get_relations(session_id: str) -> list[dict]:
    """Return all relations for a session as [{from, to, label}]."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("SELECT from_title, to_title, label FROM relations WHERE session_id = :sid"),
            {"sid": session_id},
        )
        return [{"from": r.from_title, "to": r.to_title, "label": r.label} for r in rows]


def upsert_relation(session_id: str, from_title: str, to_title: str, label: str) -> None:
    """Insert a single relation if it doesn't exist."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO relations (session_id, from_title, to_title, label)
                VALUES (:sid, :from_title, :to_title, :label)
                ON CONFLICT (session_id, from_title, to_title, label) DO NOTHING
            """),
            {"sid": session_id, "from_title": from_title, "to_title": to_title, "label": label},
        )
        conn.commit()


def bulk_upsert_relations(session_id: str, rels: list[tuple[str, str, str]]) -> None:
    """Batch-insert (from_title, to_title, label) tuples — skips existing rows."""
    if not rels:
        return
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO relations (session_id, from_title, to_title, label)
                VALUES (:sid, :from_title, :to_title, :label)
                ON CONFLICT (session_id, from_title, to_title, label) DO NOTHING
            """),
            [
                {"sid": session_id, "from_title": f, "to_title": t, "label": l}
                for f, t, l in rels
            ],
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Progress store (S5)
# ---------------------------------------------------------------------------

def get_progress(session_id: str) -> dict:
    """Return the current progress dict for a session, or {} if none exists."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        row = conn.execute(
            text("SELECT data FROM ingest_progress WHERE session_id = :sid"),
            {"sid": session_id},
        ).fetchone()
        if row is None:
            return {}
        data = row.data
        return dict(data) if data else {}


def set_progress(session_id: str, data: dict) -> None:
    """Upsert the progress dict for a session."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO ingest_progress (session_id, data, updated_at)
                VALUES (:sid, CAST(:data AS jsonb), now())
                ON CONFLICT (session_id) DO UPDATE SET
                    data       = EXCLUDED.data,
                    updated_at = now()
            """),
            {"sid": session_id, "data": json.dumps(data)},
        )
        conn.commit()


def delete_progress(session_id: str) -> None:
    """Remove the progress row for a session."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("DELETE FROM ingest_progress WHERE session_id = :sid"),
            {"sid": session_id},
        )
        conn.commit()


def cleanup_old_progress(days: int = 7) -> None:
    """Delete progress rows not updated in the last `days` days."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("DELETE FROM ingest_progress WHERE updated_at < now() - make_interval(days => :days)"),
            {"days": days},
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Migration helper
# ---------------------------------------------------------------------------

def migrate_from_json(session_id: str, json_path: str) -> None:
    """Read an index.json and insert all pages/relations into the DB.

    Safe to call multiple times — ON CONFLICT DO NOTHING skips existing rows.
    """
    from sqlalchemy import text

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    raw_pages = data.get("pages", {})
    raw_rels = data.get("relations", [])

    engine = get_engine()
    with engine.connect() as conn:
        for title, value in raw_pages.items():
            if isinstance(value, str):
                content = value
                summary = source_doc = ""
                contradiction_flagged = False
                variants_json = None
            else:
                content = value.get("content", "")
                summary = value.get("summary", "")
                source_doc = value.get("source_doc", "")
                contradiction_flagged = bool(value.get("contradiction_flagged", False))
                v = value.get("variants")
                variants_json = json.dumps(v) if v else None

            conn.execute(
                text("""
                    INSERT INTO pages
                        (session_id, title, content, summary, source_doc,
                         contradiction_flagged, variants, char_count)
                    VALUES
                        (:sid, :title, :content, :summary, :source_doc,
                         :cf, CAST(:variants AS jsonb), :char_count)
                    ON CONFLICT (session_id, title) DO NOTHING
                """),
                {
                    "sid": session_id,
                    "title": title,
                    "content": content,
                    "summary": summary,
                    "source_doc": source_doc,
                    "cf": contradiction_flagged,
                    "variants": variants_json,
                    "char_count": len(content),
                },
            )

        for rel in raw_rels:
            conn.execute(
                text("""
                    INSERT INTO relations (session_id, from_title, to_title, label)
                    VALUES (:sid, :from_title, :to_title, :label)
                    ON CONFLICT (session_id, from_title, to_title, label) DO NOTHING
                """),
                {
                    "sid": session_id,
                    "from_title": rel.get("from", ""),
                    "to_title": rel.get("to", ""),
                    "label": rel.get("label", ""),
                },
            )

        conn.commit()

    logger.info(
        "Migrated session %s from JSON: %d pages, %d relations",
        session_id, len(raw_pages), len(raw_rels),
    )


# ---------------------------------------------------------------------------
# S2: FTS cross-reference helpers (Phase 4)
# ---------------------------------------------------------------------------

def find_pages_mentioning_title(session_id: str, title: str) -> list[str]:
    """Return titles of pages whose content mentions the given title.

    Uses the GIN-indexed content_tsv column for O(log N) lookup instead of
    the O(N) Python substring scan.  Returns [] if the title produces no FTS
    tokens (e.g. a single stop-word title).
    """
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT title FROM pages
                WHERE session_id = :sid
                  AND title      != :title
                  AND content_tsv @@ plainto_tsquery('english', :tokens)
            """),
            {"sid": session_id, "title": title, "tokens": title},
        )
        return [row.title for row in rows]


# ---------------------------------------------------------------------------
# S3: Page compaction helpers (Phase 4)
# ---------------------------------------------------------------------------

def find_pages_due_for_compaction(
    session_id: str, append_threshold: int, char_threshold: int
) -> list[dict]:
    """Return pages that exceed the compaction thresholds."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT title, content, summary, variants, append_count, char_count, source_doc
                FROM pages
                WHERE session_id = :sid
                  AND (
                    append_count >= :at
                    OR (append_count >= 2 AND char_count >= :ct)
                  )
                ORDER BY append_count DESC, char_count DESC
            """),
            {"sid": session_id, "at": append_threshold, "ct": char_threshold},
        )
        return [dict(row._mapping) for row in rows]


def reset_page_after_compaction(
    session_id: str,
    title: str,
    content: str,
    summary: str,
    contradiction_flagged: bool,
) -> None:
    """Replace page content after re-synthesis and reset append_count to 0."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("""
                UPDATE pages
                SET content               = :content,
                    summary               = :summary,
                    contradiction_flagged = :cf,
                    append_count          = 0,
                    char_count            = :char_count,
                    variants              = NULL,
                    last_modified         = now()
                WHERE session_id = :sid AND title = :title
            """),
            {
                "sid": session_id,
                "title": title,
                "content": content,
                "summary": summary,
                "cf": contradiction_flagged,
                "char_count": len(content),
            },
        )
        conn.commit()


# ---------------------------------------------------------------------------
# S4: Structured contradiction storage (Phase 4)
# ---------------------------------------------------------------------------

def upsert_contradiction(
    session_id: str,
    page_title: str,
    claim: str | None,
    value_a: str | None,
    source_a: str | None,
    value_b: str | None,
    source_b: str | None,
) -> None:
    """Record a detected contradiction for a page."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO contradictions
                    (session_id, page_title, claim, value_a, source_a, value_b, source_b)
                VALUES (:sid, :title, :claim, :va, :sa, :vb, :sb)
            """),
            {
                "sid": session_id, "title": page_title,
                "claim": claim, "va": value_a, "sa": source_a,
                "vb": value_b, "sb": source_b,
            },
        )
        conn.commit()


# ---------------------------------------------------------------------------
# C7: Metadata helpers (Phase 4)
# ---------------------------------------------------------------------------

_METADATA_COLUMNS = (
    "governing_law", "jurisdiction", "effective_date", "termination_notice",
    "liability_cap", "ip_ownership", "parties", "auto_renewal",
    "notice_period", "payment_terms", "matter_reference",
)


def upsert_metadata(session_id: str, doc_name: str, metadata: dict) -> None:
    """Store document-level metadata extracted at ingest time.

    `doc_name` is used as the `title` key — Review mode looks up by doc_name.
    Only non-None values are written; existing values are preserved for fields
    not present in the new metadata dict.
    """
    if not metadata:
        return
    from sqlalchemy import text
    engine = get_engine()
    # Build dynamic SET clause for non-None fields only
    updates = {k: metadata[k] for k in _METADATA_COLUMNS if metadata.get(k) is not None}
    if not updates:
        return
    set_clause = ", ".join(f"{k} = COALESCE(:{k}, page_metadata.{k})" for k in updates)
    params = {"sid": session_id, "title": doc_name, **updates}
    with engine.connect() as conn:
        conn.execute(
            text(f"""
                INSERT INTO page_metadata (session_id, title, {', '.join(updates)})
                VALUES (:sid, :title, {', '.join(':' + k for k in updates)})
                ON CONFLICT (session_id, title) DO UPDATE SET {set_clause}
            """),
            params,
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Chat messages (conversational UX)
# ---------------------------------------------------------------------------

def insert_message(
    session_id: str,
    role: str,
    content: str,
    msg_type: str = "text",
    metadata: dict | None = None,
) -> int:
    """Insert a chat message and return its id."""
    from sqlalchemy import text
    engine = get_engine()
    meta_json = json.dumps(metadata) if metadata is not None else None
    with engine.connect() as conn:
        row = conn.execute(
            text("""
                INSERT INTO chat_messages (session_id, role, content, msg_type, metadata)
                VALUES (:sid, :role, :content, :msg_type, CAST(:metadata AS jsonb))
                RETURNING id
            """),
            {
                "sid": session_id, "role": role, "content": content,
                "msg_type": msg_type, "metadata": meta_json,
            },
        ).fetchone()
        conn.commit()
        return row.id


def get_messages(session_id: str, limit: int = 50) -> list[dict]:
    """Return chat messages for a session, oldest first."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT id, role, content, msg_type, metadata, created_at
                FROM chat_messages
                WHERE session_id = :sid
                ORDER BY created_at ASC
                LIMIT :limit
            """),
            {"sid": session_id, "limit": limit},
        )
        result = []
        for r in rows:
            msg = {
                "id": r.id,
                "role": r.role,
                "content": r.content,
                "msg_type": r.msg_type,
                "metadata": r.metadata if r.metadata else {},
                "created_at": r.created_at.isoformat() if r.created_at else "",
            }
            result.append(msg)
        return result


def get_recent_context(session_id: str, n: int = 5) -> list[dict]:
    """Return the last n messages for building conversation context."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT role, content, msg_type
                FROM (
                    SELECT role, content, msg_type, created_at
                    FROM chat_messages
                    WHERE session_id = :sid AND msg_type IN ('text', 'answer')
                    ORDER BY created_at DESC
                    LIMIT :n
                ) sub
                ORDER BY created_at ASC
            """),
            {"sid": session_id, "n": n},
        )
        return [{"role": r.role, "content": r.content, "msg_type": r.msg_type} for r in rows]


def delete_messages(session_id: str) -> None:
    """Delete all chat messages for a session."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(
            text("DELETE FROM chat_messages WHERE session_id = :sid"),
            {"sid": session_id},
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Source document helpers
# ---------------------------------------------------------------------------

def get_source_docs(session_id: str) -> list[str]:
    """Return distinct source_doc values for a session."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT DISTINCT source_doc FROM pages
                WHERE session_id = :sid AND source_doc != ''
            """),
            {"sid": session_id},
        )
        return [r.source_doc for r in rows]


# ---------------------------------------------------------------------------
# Source positions (citation exact-location support)
# ---------------------------------------------------------------------------

def store_page_map(session_id: str, source_doc: str, page_map: list[dict]) -> None:
    """Store page-level character positions for a source document."""
    if not page_map:
        return
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        for entry in page_map:
            conn.execute(
                text("""
                    INSERT INTO source_positions (session_id, source_doc, page_num, char_start, char_end)
                    VALUES (:sid, :doc, :pn, :cs, :ce)
                    ON CONFLICT (session_id, source_doc, page_num) DO UPDATE SET
                        char_start = EXCLUDED.char_start,
                        char_end   = EXCLUDED.char_end
                """),
                {
                    "sid": session_id, "doc": source_doc,
                    "pn": entry["page_num"], "cs": entry["char_start"], "ce": entry["char_end"],
                },
            )
        conn.commit()


def get_page_map(session_id: str, source_doc: str) -> list[dict]:
    """Return page positions for a source document."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT page_num, char_start, char_end
                FROM source_positions
                WHERE session_id = :sid AND source_doc = :doc
                ORDER BY page_num
            """),
            {"sid": session_id, "doc": source_doc},
        )
        return [{"page_num": r.page_num, "char_start": r.char_start, "char_end": r.char_end} for r in rows]


def find_quote_position(session_id: str, source_doc: str, quote_text: str) -> dict:
    """Find the page number and character offset of a quote in a source document.

    Loads the document text from the upload path, does a fuzzy match, then maps
    the offset back to a PDF page using the stored page_map.
    """
    import re as _re

    page_map = get_page_map(session_id, source_doc)
    if not page_map:
        return {"found": False, "page_num": 0, "char_offset": 0}

    # We need the full document text to search in. Load from the uploads directory.
    import config as _cfg
    import os as _os
    from services.reader import read_file as _read

    target_path = None
    prefix = f"{session_id}_"
    upload_dir = _cfg.UPLOAD_PATH
    doc_basename = source_doc.replace("/", "_").replace("\\", "_")
    if _os.path.isdir(upload_dir):
        for fname in _os.listdir(upload_dir):
            if fname.startswith(prefix) and fname.endswith(doc_basename):
                target_path = _os.path.join(upload_dir, fname)
                break
        if not target_path:
            for fname in _os.listdir(upload_dir):
                if fname.endswith(doc_basename):
                    target_path = _os.path.join(upload_dir, fname)
                    break

    if not target_path or not _os.path.exists(target_path):
        return {"found": False, "page_num": 0, "char_offset": 0}

    try:
        full_text = _read(target_path)
    except Exception:
        return {"found": False, "page_num": 0, "char_offset": 0}

    # Normalize for fuzzy matching
    norm_text = _re.sub(r'\s+', ' ', full_text.lower())
    norm_quote = _re.sub(r'\s+', ' ', quote_text.strip().lower())

    idx = norm_text.find(norm_quote)
    if idx == -1 and len(norm_quote) > 40:
        idx = norm_text.find(norm_quote[:40])

    if idx == -1:
        return {"found": False, "page_num": 0, "char_offset": 0}

    # Map offset to page number
    matched_page = 1
    for entry in page_map:
        if entry["char_start"] <= idx < entry["char_end"]:
            matched_page = entry["page_num"]
            break
    else:
        if page_map:
            matched_page = page_map[-1]["page_num"]

    return {"found": True, "page_num": matched_page, "char_offset": idx}


def get_metadata(session_id: str, doc_name: str) -> dict:
    """Return the metadata dict for a document, or {} if none stored."""
    from sqlalchemy import text
    engine = get_engine()
    with engine.connect() as conn:
        row = conn.execute(
            text(f"""
                SELECT {', '.join(_METADATA_COLUMNS)}
                FROM page_metadata
                WHERE session_id = :sid AND title = :title
            """),
            {"sid": session_id, "title": doc_name},
        ).fetchone()
        if row is None:
            return {}
        return {k: v for k, v in zip(_METADATA_COLUMNS, row) if v is not None}
